### ISSUE TITLE
Hactoberfest 2023

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/Java-DSA-InterviewPrep#10]
Hi Contributors,

This Repository is open for Hactoberfest2023, will be awaiting for your PRs, in case if any queries you can discuss here in this issue.

If no issue is there, then make a issue which you think is good to raise.

We will be accepting code and no-code PRs.

**Comment by SAURABHTIWARIVBSPU** [comment]
Hello sir, I hope you are doing well. Sir please share a problem in issue section . here is no problem  please guide me back

**Comment by rohan472000** [comment]
Hi @SAURABH, you can contribute to codes by adding new algo or correcting existing algo by adding description or comments to them, if interested in no-code contribution then  edit readme page of this repo.

If anything else is there on your mind, feel free to discuss.

**Comment by SAURABHTIWARIVBSPU** [comment]
public class Main {
  public static void main(String[] args) {
    String originalStr = "Hello";
    String reversedStr = "";
    System.out.println("Original string: " + originalStr);
        
    for (int i = 0; i < originalStr.length(); i++) {
      reversedStr = originalStr.charpublic class Main {
  public static void main(String[] args) {
    String originalStr = "Hello";
    String reversedStr = "";
    System.out.println("Original string: " + originalStr);
        
    for (int i = 0; i < originalStr.length(); i++) {
      reversedStr = originalStr.charAt(i) + reversedStr;
    }
    
    System.out.println("Reversed string: "+ reversedStr);
  }
}

**Comment by charlie8658** [comment]
> public class Main { public static void main(String[] args) { String originalStr = "Hello"; String reversedStr = ""; System.out.println("Original string: " + originalStr);
> 
> ```
> for (int i = 0; i < originalStr.length(); i++) {
>   reversedStr = originalStr.charpublic class Main {
> ```
> 
> public static void main(String[] args) { String originalStr = "Hello"; String reversedStr = ""; System.out.println("Original string: " + originalStr);
> 
> ```
> for (int i = 0; i < originalStr.length(); i++) {
>   reversedStr = originalStr.charAt(i) + reversedStr;
> }
> 
> System.out.println("Reversed string: "+ reversedStr);
> ```
> 
> } }

@SAURABHTIWARIVBSPU why pasting code here, just discuss what you want to implement and we will happy to help you.

**Comment by whitehawk0910** [comment]
I am uploading Dijkstra's algorithm in the repo

**Comment by rohan472000** [comment]
@whitehawk0910 if you are interested then can you take up issue #14 ???

**Comment by charlie8658** [comment]
i have raised a PR for it.

**Comment by Saifullah00** [comment]
Can I upload Top interview problems on String  (folder) as there is no such folder on String problems.
And in real interview I came across such problems.

**Comment by rohan472000** [comment]
> Can I upload Top interview problems on String (as a folder) as there is no such folder on String problems. And in real interview I came across such problems.

@Saifullah00 sure, go ahead :)

**Comment by whitehawk0910** [comment]
> @whitehawk0910 if you are interested then can you take up issue #14 ???

ya  I will do it.

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by rohan472000** [comment]
@nancy-singh10 which issue??? As all issues are assigned.

**Comment by madm234** [comment]
Can I add important graph algorithms like:
1. Kahn's algo(BFS), DFS for Topological Sort
2. Prim's algo, Kruskal's algo for MST
3. Dijkistra's algo(already added), Bellman Ford and Floyd Warshall algo for shortest path.
properly inside the Graph folder. Just a suggestion from my side.

**Comment by rohan472000** [comment]
@madm234 sure..go ahead.

**Comment by SheetalPunyani** [comment]
> Hi Contributors,
> 
> This Repository is open for Hactoberfest2023, will be awaiting for your PRs, in case if any queries you can discuss here in this issue.
> 
> If no issue is there, then make a issue which you think is good to raise.
> 
> We will be accepting code and no-code PRs.

hey i want to add questions on topics so should l create a issue then after u assign lt then only pr's will be made or l can dirctly make pr?

**Comment by rohan472000** [comment]
Well.. as you wish, but better raise a issue first, so that others can also look into it and then raise PR.

**Comment by avinashkrishna07** [comment]
Hii @rohan472000 I'm interested in contributing to no code PR i.e in README.md file. Can I directly make a pull request or will you assign this issue to me ?
Thank you!

**Comment by rohan472000** [comment]
@avinashkrishna07 make a PR..

**Comment by YogitaDose** [comment]
I am interested in contributing Prim's algo, Kruskal's algo for MST

**Comment by rohan472000** [comment]
> I am interested in contributing Prim's algo, Kruskal's algo for MST
> 
> 

Go ahead and raise PR.

**Comment by ArcheR1901** [comment]
please assign me this issue. I have some codes that can help people coming new to java

**Comment by rohan472000** [comment]
> please assign me this issue. I have some codes that can help people coming new to java

Kindly go ahead and raise PR.

**Comment by madm234** [comment]
@rohan472000 Why you have still put the hactoberfest labels. Your repo has already been excluded from hactoberfest. I got this msg after 2 days of merging pr. 

![Screenshot_2023-10-08-15-23-50-951_com android chrome](https://github.com/rohan472000/Java-DSA-InterviewPrep/assets/88799492/3aa638c3-c141-480b-9f17-24fd49b7efe4)

**Comment by rohan472000** [comment]
yeah I seen that yesterday, this repo is following all guidelines for hacktoberfest, I'm not sure why it is excluded, is it because someone have reported because I have closed many PRs due to lack of meaning in them.

**Comment by madm234** [comment]
@rohan472000 Full message. 
![Uploading IMG_20231008_152955.jpg…]()

**Comment by madm234** [comment]
Full message it is showing
![IMG_20231008_152955](https://github.com/rohan472000/Java-DSA-InterviewPrep/assets/88799492/703bc26f-441d-44f4-af98-6d31f2f618d5)

**Comment by rohan472000** [comment]
Thats also my question, what rules this repo is n0t following..?

**Comment by rohan472000** [comment]
Closing for above reasons, already raised PRs will be reviewed and merged.
