### ISSUE TITLE
Reverse a string in java

### ISSUE THREAD

**Issue by SAURABHTIWARIVBSPU** [rohan472000/Java-DSA-InterviewPrep#12]

**Comment by SAURABHTIWARIVBSPU** [comment]
public class Main {
  public static void main(String[] args) {
    String originalStr = "Hello";
    String reversedStr = "";
    System.out.println("Original string: " + originalStr);
        
    for (int i = 0; i < originalStr.length(); i++) {
      reversedStr = originalStr.charpublic class Main {
  public static void main(String[] args) {
    String originalStr = "Hello";
    String reversedStr = "";
    System.out.println("Original string: " + originalStr);
        
    for (int i = 0; i < originalStr.length(); i++) {
      reversedStr = originalStr.charAt(i) + reversedStr;
    }
    
    System.out

**Comment by SAURABHTIWARIVBSPU** [comment]
Sir please accept this for as a my pull request

**Comment by rohan472000** [comment]
Reverse string is already there in repo..kindly check first..

**Comment by rohan472000** [comment]
And don't raise a issue....first discuss and then raise a PR.
