### ISSUE TITLE
Make PR template 

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/Java-DSA-InterviewPrep#14]
For this repo, I need a good PR template which has all necessary checkboxes so that every PR will be easily understandable to viewers.

**Comment by rohan472000** [comment]
@charlie8658 assigned to you.

**Comment by SAURABHTIWARIVBSPU** [comment]
Sir please can you assign me this issue #14

**Comment by rohan472000** [comment]
> Sir please can you assign me this issue #14

**Comment by SAURABHTIWARIVBSPU** [comment]
Description of PR:
Please make sure to do the following:
- Read CONTRIBUTING.md: Take a look at the project guidelines in CONTRIBUTING.md and make sure you understand them.
- Original Work: Your PR should include your own original work. Avoid plagiarism.
- Automated Tests: Make sure your PR passes the automated tests and doesn't break any existing functionality.
- One Algorithm per Pull Request: If you're making changes to multiple algorithms, please open separate PRs for each one.
- File Placement: Put new Python files in the appropriate project directories.
- Naming Conventions: Follow Python naming conventions to ensure clarity.
- Type Annotations: Use Python type hints to annotate parameters and return values.
- Doctests: Include doctests to test the correctness of your code.
- Include Explanatory URLs: If you're introducing new algorithms, provide relevant sources as URLs.
- Resolve Issues: If your PR resolves any issues, mention the respective issue numbers (e.g., "Fixes #ISSUE-NUMBER"). #16

**Comment by rohan472000** [comment]
Raise a PR, don't paste it here.

**Comment by rohan472000** [comment]
What's update @SAURABHTIWARIVBSPU

**Comment by rohan472000** [comment]
Should I unassign you @SAURABHTIWARIVBSPU ?????
