### ISSUE TITLE
Top interview questions on Strings

### ISSUE THREAD

**Issue by Saifullah00** [rohan472000/Java-DSA-InterviewPrep#18]
I want to make a folder on String where I will update top String problem.
As I requested previously under Hactoberfest issue please assign me this.
Thank you

**Comment by rohan472000** [comment]
@Saifullah00 go ahead, also put other string questions/algo which are present already in repo into that folder if possible.

**Comment by Saifullah00** [comment]
Ok 💯

**Comment by hitali-khachane** [comment]
Can u please Assign me this issue

**Comment by rohan472000** [comment]
@hitali-khachane go ahead.

**Comment by yashita89** [comment]
Hey I would like to contribute pls assign me with this

**Comment by rohan472000** [comment]
@yashita89 go ahead and raise PR.
