### ISSUE TITLE
I would like to add conceptual leetcode question on various topics 

### ISSUE THREAD

**Issue by Saikat2407** [rohan472000/Java-DSA-InterviewPrep#44]
@rohan472000 assign me this issue

**Comment by rohan472000** [comment]
@Saikat2407 go ahead.

**Comment by dot-D69** [comment]
Please sir assign me this issue

**Comment by dot-D69** [comment]
@rohan472000  I understand
I just thought having the code for cpp would be a good addition

If you change your mind then do tell
Thank you

**Comment by rohan472000** [comment]
Appreciate your enthusiasm buddy, but this repo maintains only java code :)
