### ISSUE TITLE
Merge Sort in sorting sub repo

### ISSUE THREAD

**Issue by amansheoran15** [rohan472000/Java-DSA-InterviewPrep#47]
I'd like to add merge sort under sorting sub folder.

**Comment by rohan472000** [comment]
I thought nk it is there, check once, try to improve that and put it in that folder.

**Comment by amansheoran15** [comment]
![image](https://github.com/rohan472000/Java-DSA-InterviewPrep/assets/91284283/640fe193-09de-48ac-be14-41c61f76f73f)

Merge sort is missing

**Comment by rohan472000** [comment]
Ok...do it and also few sorting algos are outside the folders , plz put that into sorting folder also.
