### ISSUE TITLE
Add 40+ different types of Sorting Algorithm in JAVA

### ISSUE THREAD

**Issue by Pankaj-Bind** [rohan472000/Java-DSA-InterviewPrep#49]
assign me this work I can create a folder that have 40+different types of sorting algorithm.

and I ensure that you will be happy with my work.

**Comment by rohan472000** [comment]
Well there is a folder named sorting, kindly do your work there, I'll be happy to review.

**Comment by Pankaj-Bind** [comment]
thanks
