### ISSUE TITLE
Disjoinset DataSet Template

### ISSUE THREAD

**Issue by knockcat** [rohan472000/Java-DSA-InterviewPrep#66]
Hello, sir, I want to add Disjoint set Data structure template, please assign me with this task.

**Comment by benteer** [comment]
I will add disjoint set data structure

**Comment by rohan472000** [comment]
> I will add disjoint set data structure

Sure..go ahead.

**Comment by knockcat** [comment]
Sir I have made the pull request

**Comment by knockcat** [comment]
@github-actions
ruff / ruff (pull_request) Failing after 7s   
this check is failing i don't know , please look in the issue sir.

**Comment by rohan472000** [comment]
Let me check.

**Comment by rohan472000** [comment]
@knockcat issue fixed.
