### ISSUE TITLE
implementation of graph in java

### ISSUE THREAD

**Issue by srexrg** [rohan472000/Java-DSA-InterviewPrep#67]
I would like to add implementation of graph in java..Please add hacktoberfest label and assign me

**Comment by rohan472000** [comment]
Go ahead raise PR in graph folder.

**Comment by srexrg** [comment]
thanks

**Comment by yashita89** [comment]
hey i would like to contibute here.pls assign me with this

**Comment by rohan472000** [comment]
@PriyankaPatel1612 sure go ahead and raise PR, don't wait to get assigned.

**Comment by shivamk23** [comment]
Hey Rohan ,
I would like to contribute can you merge my code i hope i write an optimized code.

**Comment by rohan472000** [comment]
> Hey Rohan ,
> I would like to contribute can you merge my code i hope i write an optimized code.

Will be reviewed soon, then after approval it will be merged.
