### ISSUE TITLE
Imrpove Readme.md: Table of content is not redirecting to its topic

### ISSUE THREAD

**Issue by ayushsarode** [rohan472000/Java-DSA-InterviewPrep#82]
Hey! @rohan472000! The purpose of a Table of Contents is to provide readers with a quick and efficient way to navigate through the document's content. However, in its current state, the Table of Contents fails to fulfill this essential role. When readers click on the links or page numbers listed in the Table of Contents, they do not get redirected to the corresponding topics within the document.

I want to work on this Issue, Can you assign this to me?

**Comment by rohan472000** [comment]
@ayushsarode , thanks for showing concern about this repos readme, which is true that is not correctly curated, as part of hacktoberfest many contributors came and did negligible changes on readme just to get their PR accepted.

But if u are interested to make it even better, plz go ahead and raise PR :)

**Comment by ayushsarode** [comment]
> @ayushsarode , thanks for showing concern about this repos readme, which is true that is not correctly curated, as part of hacktoberfest many contributors came and did negligible changes on readme just to get their PR accepted.
> 
> But if u are interested to make it even better, plz go ahead and raise PR :)

Certainly, for the sake of garnering favorable public relations, some individuals may engage in activities that lack credibility. I aim to enhance your README documentation to make it more effective.
Thank you!

**Comment by ayushsarode** [comment]
Also do you want visitor counter on the repo?

**Comment by rohan472000** [comment]
> Also do you want visitor counter on the repo?

Ya sure.
