### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/Java-DSA-InterviewPrep#9]
can someone fix/update its README.md as many topics are not included in it.

Also, put algo which are outside of folder to required folder.

**Comment by MrigankaGhosh** [comment]
I may help you out with the documentation. Please, elaborate on the issue that you posted and assign the task to me.

**Comment by rohan472000** [comment]
Thank you for showing interest in fixing the issues. I would appreciate your help in fixing the README.md file to make it more informative and user-friendly, by explaining/defining topics included in repo. Additionally, it would be great if you could place the .java files in their correct directory. If needed, please feel free to create a new directory for any unknown files.

Also, if you want to contribute any new problems in DSA which is not there in repo, feel free to make a PR.

Let me know if you have any questions or need any further information from my side.

**Comment by SheetalPunyani** [comment]
hey l can update readme.md file can you assign it to me.

**Comment by rohan472000** [comment]
@SheetalPunyani assigned.

**Comment by avinashkrishna07** [comment]
Hii @rohan472000 Can you please assign this to me, as i'm interested and would like to contribute on this project.
Thank you!

**Comment by rohan472000** [comment]
@avinashkrishna07 raise PR directly.

**Comment by dikshant182004** [comment]
hii @MrigankaGhosh can u plz assign this issue to me
